language: python
python:
- "2.6"
- "2.7"
- "pypy"
install:
- if [ "$TRAVIS_PYTHON_VERSION" = '2.6' ]; then SPHINX_VERSION=1.4.9; fi
- pip install sphinx${SPHINX_VERSION:+==$SPHINX_VERSION}
script:
- python -m doctest -v grapevine.py
- PYTHONPATH=$PWD sphinx-build -b doctest doc/api tmp

# vim:ts=2 sts=2 sw=2 et
