language: python
python:
- "2.6"
- "2.7"
- "pypy"
install:
- pip install sphinx
script:
- python -m doctest -v grapevine.py
- PYTHONPATH=$PWD sphinx-build -b doctest doc tmp

# vim:ts=2 sts=2 sw=2 et
